### ISSUE TITLE
import MicrosoftPizza.json to LUIS is invalid

### ISSUE THREAD

**Issue by ofirEdi** [Azure/pizza_luis_bot#1]
Hi,
When trying to import LUIS app from your repository (MicrosoftPizza.json) i'm getting the following error from LUIS:

BadArgument: Failed to parse application json. Parameter name: applicationJsonString 

any ideas how to modify MicrosoftPizza.json in order to succefully import the app to LUIS?
![LUIS](https://user-images.githubusercontent.com/38286442/71993187-56deec80-323f-11ea-8823-fb803089f6bb.PNG)

**Comment by hazemelh** [comment]
@ofirEdi Hello, Please use preview.luis.ai to import the application as this uses new features, not supported in the current luis.ai portal.
